"""Curated knowledge catalog (50+ entries).

Each entry: (slug, version, type, industry, title, content, condition,
recommendation, evidence). industry=None means cross-industry. Multiple rows
with the same slug demonstrate versioning (older versions archived at seed).
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Tuple

Entry = Tuple[str, int, str, Optional[str], str, str, Optional[str], Optional[str], Optional[str]]

CATALOG: List[Entry] = [
    # ---------------- metric definitions ----------------
    ("metric_roi", 1, "metric_definition", None, "ROI 投入产出比",
     "ROI=广告带来的成交金额(GMV)×毛利率÷广告花费(spend)，衡量每一元广告费的毛利回报，低于1意味着投放亏损。",
     "诊断广告效率、判断提预算是否安全时使用", "ROI 连续低于盈亏线先降本，再考虑放量", "平台广告经营通用口径"),
    ("metric_ctr", 1, "metric_definition", None, "CTR 点击率",
     "CTR=点击量÷曝光量，反映素材与人群的匹配度，行业均值随品类不同差异明显。",
     "分析素材吸引力、流量精准度时使用", "CTR 低于行业均值优先优化素材与定向", "平台广告经营通用口径"),
    ("metric_cvr", 1, "metric_definition", None, "CVR 转化率",
     "CVR=成交订单量÷点击量，受商品力、价格、评价、详情页与库存共同影响。",
     "点击高但成交弱时使用", "CVR 低先查商品评分、价格带与承接页，而非加预算", "平台广告经营通用口径"),
    ("metric_cpm", 1, "metric_definition", None, "CPM 千次曝光成本",
     "CPM=花费÷曝光量×1000，由竞价激烈程度、出价、人群质量与素材预估互动率决定。",
     "分析流量成本上涨时使用", "CPM 上涨需结合 CTR 与 ROI 判断是否素材衰退或大盘竞争加剧", "平台广告经营通用口径"),
    ("metric_cpa", 1, "metric_definition", None, "CPA 单均转化成本",
     "CPA=广告花费÷成交订单量，是控成本型商家最核心的约束指标，应与客单价和毛利率联动看。",
     "成本型商家日常监控", "CPA 高于毛利承受线时收紧定向、暂停低效计划", "平台广告经营通用口径"),
    ("metric_gmv", 1, "metric_definition", None, "GMV 成交金额",
     "GMV=成交订单量×客单价，是规模指标，不能单独判断健康度，必须与 spend 和 ROI 同时观察。",
     "看规模与增长时使用", "GMV 增长但 ROI 下滑属于花钱买量，需判断是否符合阶段目标", "平台广告经营通用口径"),
    ("metric_aov", 1, "metric_definition", None, "客单价 AOV",
     "客单价=GMV÷成交订单量，由品类价格带、凑单与关联推荐决定。",
     "分析利润空间与人群质量时使用", "低客单品类更依赖复购与连带率，不宜用高客单的 CPA 标准要求", "平台广告经营通用口径"),
    ("metric_repurchase", 1, "metric_definition", None, "复购率",
     "复购率=周期内再次成交客户÷成交客户，反映商品力与人群沉淀，快消与食品饮料显著高于耐用消费品。",
     "评估长期经营质量时使用", "复购率低的品类要把首单 CPA 压得更低才能盈利", "平台广告经营通用口径"),
    ("metric_fatigue", 1, "metric_definition", None, "素材疲劳度",
     "素材疲劳表现为同一素材在线 7 天后 CTR 趋势性下滑、CPM 抬升，与曝光人群重复触达有关。",
     "CTR 持续下滑、素材在线超过 7 天时使用", "疲劳素材应及时替换或迭代，而不是靠加预算硬撑", "平台广告经营通用口径"),
    ("metric_spend_rate", 1, "metric_definition", None, "预算消耗率",
     "预算消耗率=实际花费÷计划预算，长期接近 100% 且 ROI 健康代表预算受限，可小幅提预算；消耗不足则先查出价与素材。",
     "判断是否应该调整预算时使用", "消耗撞线但 ROI 低于目标时禁止提预算", "平台广告经营通用口径"),

    # ---------------- diagnostic rules ----------------
    ("diag_fatigue", 1, "diagnostic_rule", None, "素材疲劳导致 CTR 下滑",
     "素材连续投放 7-14 天后，目标人群重复曝光，CTR 趋势性下降、CPM 上升，在预算不变时花费与 GMV 同步走弱。",
     "素材年龄>7天且近7日 CTR 低于前7日、CPM 走高", "暂停疲劳素材，按老素材卖点迭代新素材，先小预算测试再放量",
     "合成世界 M001 花间女装：素材疲劳叠加提预算，ROI 由约 4.1 降至 2.6"),
    ("diag_budget_cpm", 1, "diagnostic_rule", None, "提预算引发 CPM 上涨",
     "在竞价系统中短时间提高预算/出价会触达更贵的流量池，CPM 抬升；若此时素材已疲劳，CTR 同步下滑，ROI 加速恶化。",
     "提预算后 3 天内 CPM 明显抬升且 ROI 下滑", "先确认素材新鲜度与 CTR，再分批小步提预算（单次不超过 20%）",
     "合成世界 M001 验证该链路"),
    ("diag_new_product", 1, "diagnostic_rule", None, "新品爬坡期转化不稳",
     "新品上线前 2-3 周缺少销量、评价与人群积累，CTR 可能因新鲜感较高，但 CVR 波动大，整体 ROI 不稳定属正常现象。",
     "商品上线<=21天，CTR 尚可但 CVR/ROI 波动", "保持预算稳定积累基础销量与评价，不要因短期 ROI 波动频繁开关计划",
     "合成世界 M003 美妆新品增长曲线"),
    ("diag_traffic_cost", 1, "diagnostic_rule", None, "大盘流量成本上涨",
     "行业大促前或竞争加剧时，全行业 CPM 系统性抬升，表现为商家未做任何改动但 ROI 普遍下行。",
     "同行业多商家 CPM 同步上涨，CTR 基本稳定", "错峰投放、提高素材质量分、聚焦高转化人群，避免盲目高出价抢量",
     "合成世界 M004/M009 场景"),
    ("diag_season_decline", 1, "diagnostic_rule", None, "季节性需求衰退",
     "过季商品需求自然回落，曝光量与转化同步收缩，CPM 可能因转化率下降被动升高，属于需求侧问题而非投放操作问题。",
     "类目搜索热度下行、曝光与 GMV 同步下滑、多素材表现一致走弱", "缩减过季品预算，提前布局应季新品承接",
     "合成世界 M010 季节衰退商家"),
    ("diag_low_rating", 1, "diagnostic_rule", None, "商品评分低压制 CVR",
     "评分低于 4.6 或差评集中时，广告点击后的转化率显著下降，表现为 CTR 正常但 CVR 与 ROI 偏低。",
     "CTR 正常、CVR 持续偏低、商品评分偏低", "先优化商品与售后，暂缓加预算，把投放资源转向高评分商品",
     "平台经营诊断通用规则"),
    ("diag_bid_too_low", 1, "diagnostic_rule", None, "出价过低导致消耗不出去",
     "出价低于竞争所需水平时，计划预算消耗率低、曝光不足，常见于新建计划或竞争加剧后未调整出价。",
     "消耗率长期<50%、曝光量低、CTR/CVR 并不差", "小幅提升出价或放宽定向观察消耗变化，避免一步到位拉高成本",
     "平台经营诊断通用规则"),
    ("diag_traffic_structure", 1, "diagnostic_rule", None, "流量结构单一",
     "超过 70% 花费集中在单一计划或单一素材时，账户抗风险能力弱，素材一旦疲劳整体 ROI 快速下滑。",
     "计划/素材花费集中度高，头部素材年龄偏大", "搭建素材矩阵与计划梯队，用 10%-20% 预算持续测试新素材",
     "平台经营诊断通用规则"),
    ("diag_campaign_overlap", 1, "diagnostic_rule", None, "多计划重复投放",
     "同商家多个计划定向高度重叠时会内部竞价，推高自身 CPM，预算分散后每个计划都跑不出模型。",
     "同商品多计划人群重叠、CPM 高于单计划时期", "合并或差异化计划定向，按素材或人群做清晰分工",
     "平台经营诊断通用规则"),
    ("diag_cold_start", 1, "diagnostic_rule", None, "计划冷启动失败",
     "新计划前 3 天是模型学习期，频繁改价、改预算或开关会打断学习，导致探索失败、量起不来。",
     "新建计划 3 天内被多次修改且消耗低迷", "学习期内除明显异常外不做频繁调整，给足日预算（建议 ≥10 倍目标 CPA）",
     "平台经营诊断通用规则"),
    ("diag_inventory", 1, "diagnostic_rule", None, "缺货断货影响投放",
     "爆款缺货期间继续投放会浪费点击、拉低店铺体验分，恢复供货后模型也需要重新积累。",
     "库存为 0 或低库存但仍有广告消耗", "缺货商品立即暂停广告计划，供货恢复后用小预算重新激活",
     "平台经营诊断通用规则"),
    ("diag_audience_drift", 1, "diagnostic_rule", None, "人群漂移导致质量下降",
     "放量后系统探索到低相关人群，点击率尚可但转化率与客单价下降，新客质量被稀释。",
     "放量后 AOV 下降、CVR 走低、退款率上升", "收紧定向、用排除人群包过滤低质流量，观察 CVR 是否回升",
     "平台经营诊断通用规则"),

    # ---------------- business rules ----------------
    ("biz_budget_step", 1, "business_rule", None, "预算小步调整规则",
     "单次预算调整幅度建议不超过当前预算的 20%，调整后至少观察 2-3 天再决定下一步，避免触发模型重新学习与 CPM 剧烈波动。",
     "任何预算调整动作前", "单次≤20%，间隔≥48 小时", "平台投放治理规则"),
    ("biz_creative_refresh", 1, "business_rule", None, "素材更新频率",
     "成长期账户建议每周新增不少于 3-5 条新素材进入测试，始终保持 20% 预算用于探索，避免全账户同时疲劳。",
     "素材矩阵管理", "70/20/10：七成跑量、两成测试、一成创新", "平台投放治理规则"),
    ("biz_new_product_support", 1, "business_rule", None, "新品扶持节奏",
     "新品上线给予 14-21 天稳定扶持期，前 7 天积累点击与加购，8-21 天看 CVR 与 ROI 趋势再决定加投或收缩。",
     "新品计划决策", "扶持期内不按单日 ROI 决策", "平台投放治理规则"),
    ("biz_repurchase_logic", 1, "business_rule", None, "复购品类的首单容忍度",
     "高复购品类（食品、美妆耗材）可以接受首单微亏，用 90 天 LTV 评估回本；低复购耐用品必须要求首单 ROI 为正。",
     "判断 CPA/ROI 阈值时", "先按品类复购率设定差异化盈亏线", "平台投放治理规则"),
    ("biz_promo_calendar", 1, "business_rule", None, "大促节奏管理",
     "大促前 7-10 天蓄水加购、大促中放量收割、大促后 3 天 CPM 通常仍高而转化回落，应主动降预算避免节后亏损。",
     "大促前后排期", "节后主动下调预算 20%-30%", "平台投放治理规则"),
    ("biz_stop_loss", 1, "business_rule", None, "低效计划止损线",
     "连续 3 天 ROI 低于盈亏线且消耗达到学习门槛的计划应暂停，把预算集中到经过验证的计划。",
     "计划淘汰决策", "3 天+达门槛+低 ROI 三条件同时满足才暂停", "平台投放治理规则"),
    ("biz_attribution", 1, "business_rule", None, "归因口径不混用",
     "诊断必须统一归因窗口（如 7 日点击成交），不同归因口径的 ROI 不可直接比较，否则会得出错误结论。",
     "跨周期对比时", "全程固定同一归因口径", "平台投放治理规则"),
    ("biz_action_guardrail", 1, "business_rule", None, "高风险动作需确认",
     "单日预算调整超过 30%、暂停全部计划、大幅修改出价属于高风险动作，系统只能建议并需商家确认后执行。",
     "动作分级与审批", "高风险动作走人工确认", "平台安全治理规则"),

    # ---------------- best practices ----------------
    ("bp_creative_matrix", 1, "best_practice", None, "素材矩阵搭建",
     "按卖点、场景、人群、形式四个维度组合素材，每个跑量方向保留 2-3 条备份，降低单素材疲劳冲击。",
     "素材体系建设", "四维组合 + 同方向备份", "平台经营最佳实践"),
    ("bp_ab_test", 1, "best_practice", None, "A/B 测试只变一个变量",
     "每次 A/B 测试只改一个变量（素材、出价或定向），每组跑满至少 100 次转化或 7 天再判断，避免样本噪声。",
     "对比实验时", "单变量 + 足量样本 + 固定周期", "平台经营最佳实践"),
    ("bp_audience_layering", 1, "best_practice", None, "人群分层运营",
     "把人群分为核心老客、高意向加购、泛兴趣新客三层，分别匹配不同出价与素材，老客保 ROI、新客保规模。",
     "定向策略", "三层人群差异化出价", "平台经营最佳实践"),
    ("bp_dayparting", 1, "best_practice", None, "分时段投放",
     "按历史分小时转化数据分配预算，把预算集中在转化率高的时段，低转化时段降价或停投。",
     "预算分配优化", "用分小时 CVR 指导时段系数", "平台经营最佳实践"),
    ("bp_selling_points", 1, "best_practice", None, "场景化卖点表达",
     "素材前 3 秒给出使用场景与核心利益点，比单纯展示商品的素材 CTR 更高，尤其适合服饰与家居类目。",
     "素材脚本策划", "场景+利益点前置", "平台经营最佳实践"),
    ("bp_review_ops", 1, "best_practice", None, "评价运营",
     "主动引导真实好评、及时处理差评可把评分稳定在 4.8 以上，评分提升对 CVR 的拉动常常高于继续加预算。",
     "CVR 提升", "优先修评分再谈放量", "平台经营最佳实践"),
    ("bp_landing_page", 1, "best_practice", None, "承接页一致性",
     "素材卖点与详情页首屏必须一致，承接页加载慢或卖点错位会让广告流量在点击后流失。",
     "点击后转化诊断", "素材-页面卖点对齐", "平台经营最佳实践"),
    ("bp_weekly_review", 1, "best_practice", None, "7 天滚动复盘",
     "按 7 天窗口对比曝光、CTR、CPM、CVR、ROI 的趋势，避免被单日波动误导，所有结论用同一口径数据验证。",
     "例行经营复盘", "7 天窗口 + 漏斗逐层看", "平台经营最佳实践"),
    ("bp_scale_after_profit", 1, "best_practice", None, "先盈利后放量",
     "在 ROI 稳定高于盈亏线 2 周后再系统性提预算，放量过程中若 ROI 跌破阈值立即回到上一档预算。",
     "增长决策", "ROI 达标 2 周再放量", "平台经营最佳实践"),
    ("bp_fatigue_versions", 1, "best_practice", None, "素材迭代而非重复",
     "疲劳素材的替换应保留验证过的核心卖点，替换开头 3 秒、场景或人物，而非简单换背景音乐。",
     "新素材制作", "保留卖点、更换表现形式", "平台经营最佳实践"),

    # ---------------- industry insights ----------------
    ("in_womenswear_season", 1, "industry_insight", "womenswear", "女装强季节性",
     "女装受季节与上新节奏驱动明显，过季款需求快速衰退；应季新款前 10 天 CTR 通常更高，是测试素材的黄金窗口。",
     "女装商家季节切换", "上新即测素材，过季即降预算", "行业经验"),
    ("in_womenswear_style", 1, "industry_insight", "womenswear", "女装风格化素材",
     "女装素材中真人穿搭与场景化展示的 CTR 普遍高于白底图，风格统一的账号型素材长期 CPM 更稳。",
     "女装素材策划", "真人场景+统一风格", "行业经验"),
    ("in_womenswear_return", 1, "industry_insight", "womenswear", "女装退货率",
     "女装退货率偏高（尺码/色差），素材过度承诺会推高退货，诊断 ROI 时需关注退款后净 GMV。",
     "女装利润核算", "用净 GMV 评估真实 ROI", "行业经验"),
    ("in_beauty_repurchase", 1, "industry_insight", "beauty", "美妆高复购",
     "美妆耗材复购周期约 30-60 天，首单可以容忍较低 ROI，90 天 LTV 是更合理的考核口径。",
     "美妆投放阈值设定", "按 LTV 设首单 CPA 上限", "行业经验"),
    ("in_beauty_ingredient", 1, "industry_insight", "beauty", "美妆成分党素材",
     "美妆素材突出成分与功效证据的转化率更高，但功效宣称需合规，夸大宣传会被限流。",
     "美妆素材策划", "成分+证据+合规表达", "行业经验"),
    ("in_beauty_new", 1, "industry_insight", "beauty", "美妆新品爬坡",
     "美妆新品需要基础销量与真人测评背书，前 3 周 CVR 波动属正常，评价积累完成后 ROI 通常抬升。",
     "美妆新品诊断", "给足 21 天扶持期", "行业经验"),
    ("in_food_repurchase", 1, "industry_insight", "food", "食品饮料高频复购",
     "食品饮料属于高频低客单，复购与多件连带是利润来源，单包试吃装拉新、组合装提客单是常见打法。",
     "食品商家增长", "试吃拉新+组合提客单", "行业经验"),
    ("in_food_festival", 1, "industry_insight", "food", "食品节庆脉冲",
     "食品在节庆前 2 周出现明显需求脉冲，应提前备货备素材，节后需求与 CPM 同步回落需及时收预算。",
     "节庆排期", "提前 2 周蓄水", "行业经验"),
    ("in_3c_long_cycle", 1, "industry_insight", "3c", "3C 决策周期长",
     "3C 数码客单高、决策周期长，用户多次比价后下单，归因窗口需要拉长，短期 CVR 低不代表投放无效。",
     "3C 效果评估", "用长归因窗口看转化", "行业经验"),
    ("in_3c_launch", 1, "industry_insight", "3c", "3C 首发参数流",
     "3C 新品首发期参数对比与评测内容 CTR 高，首发窗口流量竞争激烈 CPM 贵，预热期加购成本更低。",
     "3C 新品上市", "预热加购+首发收割", "行业经验"),
    ("in_home_scene", 1, "industry_insight", "home", "家居场景化决策",
     "家居商品依赖空间场景理解，带尺寸与使用场景的素材 CVR 明显更高，白底图仅适合明确需求的搜索流量。",
     "家居素材策划", "场景化展示+尺寸说明", "行业经验"),
    ("in_home_season", 1, "industry_insight", "home", "家居换季需求",
     "家居收纳与床品跟随季节与搬家季波动，换季前 3 周是布局应季素材与预算的时间点。",
     "家居季节排期", "提前 3 周布局", "行业经验"),

    # ---------------- cases (versioned) ----------------
    ("case_fatigue_budget", 1, "case", "womenswear", "案例：花间女装素材疲劳误判为预算不足（v1）",
     "花间女装在素材疲劳 CTR 下滑时选择加预算，初期 GMV 回升，但 CPM 因竞价抬升、CTR 继续下滑，ROI 恶化。",
     "提预算后 ROI 不升反降", "先换素材再谈预算", "合成世界 M001，v1 初版结论"),
    ("case_fatigue_budget", 2, "case", "womenswear", "案例：花间女装素材疲劳误判为预算不足（v2）",
     "复盘补充：真正的先行指标是老素材 CTR 连续 7 天下滑，预算撞线只是结果；正确顺序是先迭代素材、CTR 企稳后再小步加预算。",
     "同案例补充先行指标", "以 CTR 7 日趋势为先行信号", "合成世界 M001 复盘 v2"),
    ("case_fatigue_budget", 3, "case", "womenswear", "案例：花间女装素材疲劳误判为预算不足（v3）",
     "最终结论：素材疲劳→CTR 下滑→提预算补量→CPM 抬升→ROI 加速下滑构成完整因果链，干预点应在素材侧而非预算侧，并需要 7 天窗口确认。",
     "完整因果链与干预点", "素材侧干预 + 7 天窗口验证", "合成世界 M001 最终版 v3"),
    ("case_new_growth", 1, "case", "beauty", "案例：美妆新品 21 天爬坡成功",
     "美妆新品保持预算稳定 21 天，第 8-14 天评价积累后 CVR 抬升，第 3 周 ROI 转正并具备放量条件。",
     "新品前 3 周 ROI 波动", "稳定扶持而非频繁开关", "合成世界 M003"),
    ("case_traffic_cost", 1, "case", None, "案例：大盘流量成本上涨期的防守",
     "行业 CPM 普涨期间，保持出价、收窄到高转化人群、提升素材质量分的商家 ROI 回撤最小；盲目高出价抢量的商家节后 ROI 明显更低。",
     "全行业 CPM 同步上涨", "防守策略优于抢量", "合成世界 M004/M009"),
    ("case_season_exit", 1, "case", None, "案例：季节衰退商家的及时转向",
     "过季商家在需求拐点出现后仍维持原预算，预算花在低转化流量上；及时把 60% 预算切到应季新品的商家整体 ROI 恢复更快。",
     "多素材表现一致走弱、类目热度下行", "预算转向应季新品", "合成世界 M010"),
]


def catalog_entries() -> List[Dict[str, Any]]:
    return [
        {
            "slug": slug,
            "version": version,
            "type": ktype,
            "industry": industry,
            "title": title,
            "content": content,
            "condition": condition,
            "recommendation": recommendation,
            "evidence": evidence,
        }
        for slug, version, ktype, industry, title, content, condition, recommendation, evidence in CATALOG
    ]
