"""badcase and feedback

Revision ID: 0aa538a7614e
Revises: 570d9bcd5bd6
Create Date: 2026-09-14 21:31:08.410958

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0aa538a7614e'
down_revision: Union[str, None] = '570d9bcd5bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=48), nullable=True),
    sa.Column('merchant_id', sa.String(length=32), nullable=True),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['trace_run.trace_id'], name=op.f('fk_feedback_trace_id_trace_run'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_index(op.f('ix_feedback_conversation_id'), 'feedback', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_feedback_merchant_id'), 'feedback', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_feedback_trace_id'), 'feedback', ['trace_id'], unique=False)
    op.create_table('badcase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('trace_id', sa.String(length=48), nullable=True),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.Column('eval_run_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.String(length=64), nullable=True),
    sa.Column('merchant_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('error_type', sa.String(length=24), nullable=False),
    sa.Column('affected_module', sa.String(length=64), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('reporter', sa.String(length=16), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_run.id'], name=op.f('fk_badcase_eval_run_id_eval_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], name=op.f('fk_badcase_feedback_id_feedback'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trace_id'], ['trace_run.trace_id'], name=op.f('fk_badcase_trace_id_trace_run'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badcase'))
    )
    op.create_index(op.f('ix_badcase_case_id'), 'badcase', ['case_id'], unique=False)
    op.create_index(op.f('ix_badcase_eval_run_id'), 'badcase', ['eval_run_id'], unique=False)
    op.create_index(op.f('ix_badcase_feedback_id'), 'badcase', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_badcase_merchant_id'), 'badcase', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_badcase_trace_id'), 'badcase', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_badcase_trace_id'), table_name='badcase')
    op.drop_index(op.f('ix_badcase_merchant_id'), table_name='badcase')
    op.drop_index(op.f('ix_badcase_feedback_id'), table_name='badcase')
    op.drop_index(op.f('ix_badcase_eval_run_id'), table_name='badcase')
    op.drop_index(op.f('ix_badcase_case_id'), table_name='badcase')
    op.drop_table('badcase')
    op.drop_index(op.f('ix_feedback_trace_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_merchant_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_conversation_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
