"""memory and knowledge with pgvector

Revision ID: 17cd1875dbf9
Revises: fbdfce9c3194
Create Date: 2026-09-13 09:47:25.750242

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '17cd1875dbf9'
down_revision: Union[str, None] = 'fbdfce9c3194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_item',
    sa.Column('knowledge_id', sa.String(length=48), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('merchant_count', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('knowledge_id', name=op.f('pk_knowledge_item')),
    sa.UniqueConstraint('slug', 'version', name='uq_knowledge_slug_version')
    )
    op.create_index(op.f('ix_knowledge_item_industry'), 'knowledge_item', ['industry'], unique=False)
    op.create_index(op.f('ix_knowledge_item_slug'), 'knowledge_item', ['slug'], unique=False)
    op.create_index(op.f('ix_knowledge_item_status'), 'knowledge_item', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_item_type'), 'knowledge_item', ['type'], unique=False)
    op.create_table('memory_item',
    sa.Column('memory_id', sa.String(length=48), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], name=op.f('fk_memory_item_merchant_id_merchant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id', name=op.f('pk_memory_item'))
    )
    op.create_index(op.f('ix_memory_item_merchant_id'), 'memory_item', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_memory_item_status'), 'memory_item', ['status'], unique=False)
    op.create_index(op.f('ix_memory_item_type'), 'memory_item', ['type'], unique=False)
    op.create_table('memory_conflict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('memory_id', sa.String(length=48), nullable=False),
    sa.Column('previous_memory_id', sa.String(length=48), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_item.memory_id'], name=op.f('fk_memory_conflict_memory_id_memory_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_conflict'))
    )
    op.create_index(op.f('ix_memory_conflict_memory_id'), 'memory_conflict', ['memory_id'], unique=False)
    op.execute(
        "CREATE INDEX ix_memory_item_embedding_hnsw ON memory_item "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_knowledge_item_embedding_hnsw ON knowledge_item "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_knowledge_item_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_memory_item_embedding_hnsw")
    op.drop_index(op.f('ix_memory_conflict_memory_id'), table_name='memory_conflict')
    op.drop_table('memory_conflict')
    op.drop_index(op.f('ix_memory_item_type'), table_name='memory_item')
    op.drop_index(op.f('ix_memory_item_status'), table_name='memory_item')
    op.drop_index(op.f('ix_memory_item_merchant_id'), table_name='memory_item')
    op.drop_table('memory_item')
    op.drop_index(op.f('ix_knowledge_item_type'), table_name='knowledge_item')
    op.drop_index(op.f('ix_knowledge_item_status'), table_name='knowledge_item')
    op.drop_index(op.f('ix_knowledge_item_slug'), table_name='knowledge_item')
    op.drop_index(op.f('ix_knowledge_item_industry'), table_name='knowledge_item')
    op.drop_table('knowledge_item')
    # ### end Alembic commands ###
