"""add deep embedding column to knowledge

Revision ID: 2eed261ea256
Revises: 56ad4bdb3d2a
Create Date: 2026-09-19 14:32:38.669713

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '2eed261ea256'
down_revision: Union[str, None] = '56ad4bdb3d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_item', sa.Column('embedding_deep', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True))
    op.create_index('ix_knowledge_item_embedding_deep_hnsw', 'knowledge_item', ['embedding_deep'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding_deep': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_item_embedding_deep_hnsw', table_name='knowledge_item', postgresql_using='hnsw', postgresql_ops={'embedding_deep': 'vector_cosine_ops'})
    op.drop_column('knowledge_item', 'embedding_deep')
    # ### end Alembic commands ###
