"""initial schema: merchants, products, campaigns, materials, performance, events

Revision ID: b0499d7771e3
Revises: 
Create Date: 2026-09-13 01:23:55.994918

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b0499d7771e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('merchant_name', sa.String(length=128), nullable=False),
    sa.Column('industry', sa.String(length=32), nullable=False),
    sa.Column('sub_industry', sa.String(length=64), nullable=True),
    sa.Column('business_stage', sa.String(length=32), nullable=False),
    sa.Column('gmv_level', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id', name=op.f('pk_merchant'))
    )
    op.create_index(op.f('ix_merchant_industry'), 'merchant', ['industry'], unique=False)
    op.create_table('business_event',
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], name=op.f('fk_business_event_merchant_id_merchant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_business_event'))
    )
    op.create_index(op.f('ix_business_event_event_time'), 'business_event', ['event_time'], unique=False)
    op.create_index(op.f('ix_business_event_event_type'), 'business_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_business_event_merchant_id'), 'business_event', ['merchant_id'], unique=False)
    op.create_table('campaign',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('campaign_name', sa.String(length=256), nullable=False),
    sa.Column('objective', sa.String(length=32), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], name=op.f('fk_campaign_merchant_id_merchant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', name=op.f('pk_campaign'))
    )
    op.create_index(op.f('ix_campaign_merchant_id'), 'campaign', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_campaign_status'), 'campaign', ['status'], unique=False)
    op.create_table('merchant_industry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('industry', sa.String(length=32), nullable=False),
    sa.Column('sub_industry', sa.String(length=64), server_default='', nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], name=op.f('fk_merchant_industry_merchant_id_merchant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_industry')),
    sa.UniqueConstraint('merchant_id', 'industry', 'sub_industry', name='uq_merchant_industry_tag')
    )
    op.create_index(op.f('ix_merchant_industry_merchant_id'), 'merchant_industry', ['merchant_id'], unique=False)
    op.create_table('performance_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gmv', sa.Float(), nullable=False),
    sa.Column('ad_spend', sa.Float(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.Column('aov', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], name=op.f('fk_performance_daily_merchant_id_merchant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_daily')),
    sa.UniqueConstraint('merchant_id', 'date', name='merchant_date')
    )
    op.create_index(op.f('ix_performance_daily_date'), 'performance_daily', ['date'], unique=False)
    op.create_index(op.f('ix_performance_daily_merchant_id'), 'performance_daily', ['merchant_id'], unique=False)
    op.create_table('product',
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('inventory', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], name=op.f('fk_product_merchant_id_merchant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_product'))
    )
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_index(op.f('ix_product_merchant_id'), 'product', ['merchant_id'], unique=False)
    op.create_table('material',
    sa.Column('material_id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('material_type', sa.String(length=32), nullable=False),
    sa.Column('material_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], name=op.f('fk_material_campaign_id_campaign'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], name=op.f('fk_material_merchant_id_merchant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_id', name=op.f('pk_material'))
    )
    op.create_index(op.f('ix_material_campaign_id'), 'material', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_material_merchant_id'), 'material', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_material_status'), 'material', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_status'), table_name='material')
    op.drop_index(op.f('ix_material_merchant_id'), table_name='material')
    op.drop_index(op.f('ix_material_campaign_id'), table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_product_merchant_id'), table_name='product')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_performance_daily_merchant_id'), table_name='performance_daily')
    op.drop_index(op.f('ix_performance_daily_date'), table_name='performance_daily')
    op.drop_table('performance_daily')
    op.drop_index(op.f('ix_merchant_industry_merchant_id'), table_name='merchant_industry')
    op.drop_table('merchant_industry')
    op.drop_index(op.f('ix_campaign_status'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_merchant_id'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_business_event_merchant_id'), table_name='business_event')
    op.drop_index(op.f('ix_business_event_event_type'), table_name='business_event')
    op.drop_index(op.f('ix_business_event_event_time'), table_name='business_event')
    op.drop_table('business_event')
    op.drop_index(op.f('ix_merchant_industry'), table_name='merchant')
    op.drop_table('merchant')
    # ### end Alembic commands ###
