"""agent trace run and span

Revision ID: d62c28a8ce79
Revises: eb9afebc4f53
Create Date: 2026-09-13 10:42:38.599168

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd62c28a8ce79'
down_revision: Union[str, None] = 'eb9afebc4f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trace_run',
    sa.Column('trace_id', sa.String(length=48), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=True),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('primary_cause', sa.String(length=48), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_clarification', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('trace_id', name=op.f('pk_trace_run'))
    )
    op.create_index(op.f('ix_trace_run_conversation_id'), 'trace_run', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_trace_run_merchant_id'), 'trace_run', ['merchant_id'], unique=False)
    op.create_table('trace_span',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=48), nullable=False),
    sa.Column('span_order', sa.Integer(), nullable=False),
    sa.Column('span_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['trace_run.trace_id'], name=op.f('fk_trace_span_trace_id_trace_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trace_span'))
    )
    op.create_index(op.f('ix_trace_span_trace_id'), 'trace_span', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trace_span_trace_id'), table_name='trace_span')
    op.drop_table('trace_span')
    op.drop_index(op.f('ix_trace_run_merchant_id'), table_name='trace_run')
    op.drop_index(op.f('ix_trace_run_conversation_id'), table_name='trace_run')
    op.drop_table('trace_run')
    # ### end Alembic commands ###
