"""tool call audit log

Revision ID: eb9afebc4f53
Revises: 17cd1875dbf9
Create Date: 2026-09-13 10:10:15.406156

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'eb9afebc4f53'
down_revision: Union[str, None] = '17cd1875dbf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_call_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=True),
    sa.Column('trace_id', sa.String(length=48), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_summary', sa.String(length=512), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_call_log'))
    )
    op.create_index(op.f('ix_tool_call_log_merchant_id'), 'tool_call_log', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_tool_call_log_tool_name'), 'tool_call_log', ['tool_name'], unique=False)
    op.create_index(op.f('ix_tool_call_log_trace_id'), 'tool_call_log', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_call_log_trace_id'), table_name='tool_call_log')
    op.drop_index(op.f('ix_tool_call_log_tool_name'), table_name='tool_call_log')
    op.drop_index(op.f('ix_tool_call_log_merchant_id'), table_name='tool_call_log')
    op.drop_table('tool_call_log')
    # ### end Alembic commands ###
