"""conversation and message

Revision ID: fbdfce9c3194
Revises: b0499d7771e3
Create Date: 2026-09-13 09:38:18.333132

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fbdfce9c3194'
down_revision: Union[str, None] = 'b0499d7771e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], name=op.f('fk_conversation_merchant_id_merchant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', name=op.f('pk_conversation'))
    )
    op.create_index(op.f('ix_conversation_merchant_id'), 'conversation', ['merchant_id'], unique=False)
    op.create_table('message',
    sa.Column('message_id', sa.String(length=48), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_id', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], name=op.f('fk_message_conversation_id_conversation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_message'))
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_conversation_merchant_id'), table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###
